services:
  # MongoDB Replica Set (without authentication for simpler setup)
  mongodb-primary:
    image: mongo:5.0
    container_name: mongodb-primary
    restart: unless-stopped
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo_primary_data:/data/db
    networks:
      - rocketchat-network

  mongodb-secondary1:
    image: mongo:5.0
    container_name: mongodb-secondary1
    restart: unless-stopped
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo_secondary1_data:/data/db
    networks:
      - rocketchat-network
    depends_on:
      - mongodb-primary

  mongodb-secondary2:
    image: mongo:5.0
    container_name: mongodb-secondary2
    restart: unless-stopped
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo_secondary2_data:/data/db
    networks:
      - rocketchat-network
    depends_on:
      - mongodb-primary

  # Rocket.Chat instances (scalable)
  rocketchat:
    image: rocket.chat:latest
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://mongodb-primary:27017,mongodb-secondary1:27017,mongodb-secondary2:27017/rocketchat?replicaSet=rs0
      MONGO_OPLOG_URL: mongodb://mongodb-primary:27017,mongodb-secondary1:27017,mongodb-secondary2:27017/local?replicaSet=rs0
      ROOT_URL: ${ROOT_URL:-http://localhost}
      PORT: 3000
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: clustered
      
      # Disable all cloud services and registration
      REGISTER_SERVER: "false"
      OVERWRITE_SETTING_Register_Server: "false"
      OVERWRITE_SETTING_Cloud_Enable: "false"
      OVERWRITE_SETTING_Cloud_Service_Agree_PrivacyTerms: "false"
      OVERWRITE_SETTING_Setup_Wizard: "completed"
      OVERWRITE_SETTING_Show_Setup_Wizard: "completed"
      
      # Disable cloud-dependent features
      OVERWRITE_SETTING_Push_enable: "false"
      OVERWRITE_SETTING_Push_enable_gateway: "false"
      OVERWRITE_SETTING_Apps_Framework_enabled: "false"
      OVERWRITE_SETTING_Statistics_reporting: "false"
      OVERWRITE_SETTING_Allow_Marketing_Emails: "false"
      
      # Local-only settings
      Accounts_UseDNSDomainCheck: "false"
      OVERWRITE_SETTING_Accounts_AllowEmailChange: "true"
      OVERWRITE_SETTING_Accounts_AllowUserProfileChange: "true"
    depends_on:
      - mongodb-primary
      - mongodb-secondary1
      - mongodb-secondary2
    networks:
      - rocketchat-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    container_name: rocketchat-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - rocketchat
    networks:
      - rocketchat-network

  # Redis for session sharing
  redis:
    image: redis:7-alpine
    container_name: rocketchat-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - rocketchat-network

networks:
  rocketchat-network:
    driver: bridge

volumes:
  mongo_primary_data:
  mongo_secondary1_data:
  mongo_secondary2_data:
  redis_data: